INSERT INTO items (`item`, `label`, `limit`, `can_remove`, `type`, `weight`, `usable`, `degradation`, `desc`) VALUES
('americanflag', 'American Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys American Flag'),
('mexicanflag', 'Mexican Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Mexican Flag'),
('canadaflag', 'Canada Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Canada Flag'),
('piratesflag', 'Pirate Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Pirate Flag'),
('transgflag', 'TRANSG Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys TRANSG Flag'),
('lgbtqflag', 'LGBTQ Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys LGBTQ Flag'),
('gypsyflag', 'Gypsy Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Gypsy Flag'),
('irishflag', 'Irish Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Irish Flag'),
('ukflag', 'Uk Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Uk Flag'),
('brflag', 'Brasil Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Brasil Flag'),
('frflag', 'France Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys France Flag'),
('itflag', 'Italia Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Italia Flag'),
('jmflag', 'Jamaica Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Jamaica Flag'),
('gerflag', 'Germany Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Germany Flag'),
('confflag', 'Confederation Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Confederation Flag'),
('unionflag', 'Union Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Union Flag'),
('lemoyne1flag', 'Lemoyne State Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Lemoyne State Flag'),
('newhannover1flag', 'New Hannover State Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys New Hannover State Flag'),
('westelizabeth1flag', 'West Elizabeth State Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys West Elizabeth State Flag'),
('newaustin1flag', 'New Austin State Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys New Austin State Flag'),
('ambarino1flag', 'Ambarino State Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Ambarino State Flag'),
('comancheflag', 'Comanche Tribe Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Comanche Tribe Flag'),
('navajoflag', 'Navajo Tribe Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Navajo Tribe Flag'),
('lakotaflag', 'Lakota Council Tribe Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Lakota Council Tribe Flag'),
('inuitflag', 'Inuit Tribe Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Inuit Tribe Flag'),
('australiaflag', 'Australia Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Australia Flag'),
('belgiumflag', 'Belgium Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Belgium Flag'),
('cataloniaflag', 'Catalonia Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Catalonia Flag'),
('chinaflag', 'China Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys China Flag'),
('cubaflag', 'Cuba Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Cuba Flag'),
('czechflag', 'Czech Republic Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Czech Republic Flag'),
('denmarkflag', 'Denmark Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Denmark Flag'),
('finlandflag', 'Finland Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Finland Flag'),
('guarmaflag', 'Guarma Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Guarma Flag'),
('hungaryflag', 'Hungary Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Hungary Flag'),
('kuwaitflag', 'Kuwait Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Kuwait Flag'),
('flandresflag', 'Flanders Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Flanders Flag'),
('newzealandflag', 'New Zealand Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys New Zealand Flag'),
('philippinesflag', 'Philippines Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Philippines Flag'),
('polandflag', 'Poland Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Poland Flag'),
('portugalflag', 'Portugal Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Portugal Flag'),
('puertoricoflag', 'Puerto Rico Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Puerto Rico Flag'),
('saudiflag', 'Saudi Arabia Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Saudi Arabia Flag'),
('serbiaflag', 'Serbia Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Serbia Flag'),
('spainflag', 'Spain Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Spain Flag'),
('swedenflag', 'Sweden Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Sweden Flag'),
('thailandflag', 'Thailand Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Thailand Flag'),
('turkeyflag', 'Turkey Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Turkey Flag'),
('ukraineflag', 'Ukraine Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Ukraine Flag'),
('whiteflag', 'White Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys White Flag'),
('whitelongflag', 'White Flag Long', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys White Flag Long'),
('redflag', 'Red Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Red Flag'),
('lemoynelongflag', 'Lemoyne Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Lemoyne Flag'),
('ambarinoflag', 'Ambarino Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys Ambarino Flag'),
('newhanoverflag', 'New Hanover Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys New Hanover Flag'),
('westelizabethflag', 'West Elizabeth Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys West Elizabeth Flag'),
('newaustinflag', 'New Austin Flag', 1, 1, 'item_standard', 0.5, 1, 0, 'Deploys New Austin Flag');